#version 450
layout(local_size_x = 1, local_size_y = 1) in;
//layout(r11f_g11f_b10f, binding = 0) uniform image2D img_input;
layout(rgba16f,  binding = 0) uniform image2D img_input;
layout(rgba16f, binding = 1) uniform image2D img_output;

void main() {

	ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);
	ivec2 up_coords = (pixel_coords / imageSize(img_output)) * (imageSize(img_input));

	vec4 upscaled = imageLoad(img_input, up_coords);

	vec4 pixel = 1 - upscaled;
	pixel.a = 1.0;

	imageStore(img_output, pixel_coords, pixel);

}