#version 450
layout(local_size_x = 1, local_size_y = 1) in;
layout(rgba16f, binding = 0) uniform image2D img_input;
layout(rgba16f, binding = 1) uniform image2D img_output;

void main() {

	ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);

	vec3 color = imageLoad(img_input, pixel_coords).xyz;

	color = color / (color + vec3(1.0)); // Tone map (HDR)
    color = pow(color, vec3(1.0/2.2)); // Gamma correct
    color = clamp(color, 0.0, 1.0);

	vec4 pixel = vec4(color, 1.0);

	imageStore(img_output, pixel_coords, pixel);
}